pub fn render_frame(
    layer: &mut LayerSystem,
    taskbar: &mut TaskbarSurface,
    wm: &mut WindowManager,
    _last_keys: &[&'static str],
    _mouse_ev: u32,
    key_ev: u32,
    fps: u32,
    mouse_mode: &str,
    cursor_x: i32,
    cursor_y: i32,
    warp_engines: &mut alloc::vec::Vec<(WinId, WarpEngine)>,
    html_engines: &mut alloc::vec::Vec<(WinId, HtmlEngine)>,
    wallpaper: Option<&[u32]>,
    cached_launcher_layer: &mut Option<Vec<u32>>,
    cached_ime_menu_layer: &mut Option<Vec<u32>>,
    taskbar_dirty: bool,
    add_progress: f32,
    remove_progress: f32,
    shift_x: f32,
    pointer_size: f32,
    hud_enabled: bool,
    bg_cache: &mut Option<Vec<u32>>,
    bg_cache_valid: bool,
    show_app_launcher: bool,
    app_list: &[alloc::string::String],
    app_icon_list: &[alloc::string::String],
    hover_apps_icon: bool,
    hover_keyboard_icon: bool,
    hover_ime_icon: bool,
    ime_hover_dirty: bool,
    search_focused: bool,
    search_query: &str,
    caret_visible: bool,
    launcher_scroll_y: usize,
    launcher_anim_phase: i8,
    launcher_anim_elapsed_ms: u32,
    launcher_scroll_changed: bool,
    launcher_only_redraw: bool,
    taskbar_only: bool,
    clock_hh: u8,
    clock_mm: u8,
    battery_pct: Option<u8>,
    ime_menu_open: bool,
    soft_keyboard: &mut SoftKeyboard,
    ime_menu_opacity: u8,
    ime_menu_selection: usize,
    ime_reading: Option<&str>,
    ime_candidates: &[alloc::string::String],
    ime_selected: usize,
) {
    render_scene(
        layer,
        taskbar,
        wm,
        _mouse_ev,
        key_ev,
        fps,
        mouse_mode,
        warp_engines,
        html_engines,
        wallpaper,
        cached_launcher_layer,
        cached_ime_menu_layer,
        taskbar_dirty,
        add_progress,
        remove_progress,
        shift_x,
        hud_enabled,
        bg_cache,
        bg_cache_valid,
        show_app_launcher,
        app_list,
        app_icon_list,
        hover_apps_icon,
        hover_keyboard_icon,
        hover_ime_icon,
        ime_hover_dirty,
        search_focused,
        search_query,
        caret_visible,
        launcher_scroll_y,
        launcher_anim_phase,
        launcher_anim_elapsed_ms,
        launcher_scroll_changed,
        launcher_only_redraw,
        taskbar_only,
        clock_hh,
        clock_mm,
        battery_pct,
        ime_menu_open,
        soft_keyboard,
        ime_menu_opacity,
        ime_menu_selection,
        ime_reading,
        ime_candidates,
        ime_selected,
    );
    let is_resizing = wm.is_any_resizing();
    cursor::draw_cursor_into_layer(layer, cursor_x, cursor_y, is_resizing, pointer_size);
}

pub fn time_diff_ns(a: &runtime::Time, b: &runtime::Time) -> u64 {
    let a_s = (a.hour() as u64) * 3600 + (a.minute() as u64) * 60 + a.second() as u64;
    let b_s = (b.hour() as u64) * 3600 + (b.minute() as u64) * 60 + b.second() as u64;
    let diff_s = b_s.saturating_sub(a_s);
    diff_s * 1_000_000_000 + (b.nanosecond() as u64).saturating_sub(a.nanosecond() as u64)
}

