[package]
name = "baram-iokit"
version = "0.1.0"
edition = "2021"

[features]
default = ["uefi"]
uefi = ["dep:uefi", "dep:uefi-raw"]
esp32s3 = ["dep:esp-hal", "dep:embedded-hal", "esp-hal/esp32s3", "baram-core/esp32s3"]

[dependencies]
baram-core = { path = "../baram-core", default-features = false }
baram-font = { path = "../baram-font", default-features = false }
baram-bsd = { path = "../baram-bsd", default-features = false }
uefi = { workspace = true, optional = true }
uefi-raw = { workspace = true, optional = true }
esp-hal = { workspace = true, optional = true }
embedded-hal = { workspace = true, optional = true }
