[package]
name = "baram-boot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bootaa64"
path = "src/main.rs"

[[bin]]
name = "baram-kernel"
path = "src/kernel.rs"

[[bin]]
name = "windowserver"
path = "src/bin/windowserver.rs"

[[bin]]
name = "font"
path = "src/bin/font.rs"

[[bin]]
name = "graphics"
path = "src/bin/graphics.rs"

[[bin]]
name = "iokit"
path = "src/bin/iokit.rs"

[[bin]]
name = "bsd"
path = "src/bin/bsd.rs"

[dependencies]
baram-core = { path = "../baram-core" }
baram-font = { path = "../baram-font" }
baram-graphics = { path = "../baram-graphics" }
baram-iokit = { path = "../baram-iokit" }
baram-bsd = { path = "../baram-bsd" }
baram-windowserver = { path = "../baram-windowserver" }
baram-kern = { path = "../baram-kern" }
nano-system = { path = "../nano-system" }
uefi = { workspace = true }
uefi-raw = { workspace = true }
libm = { workspace = true }
wana_kana = { path = "../wana-kana" }

[target.'cfg(not(target_arch = "x86_64"))'.dependencies]
png-decoder = { path = "../png-decoder" }
