using Hebron;
using Hebron.Roslyn;
using Hebron.Rust;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace StbSharp.StbTrueType.Generator
{
	static class Program
	{
		private static readonly Dictionary<string, string[]> _outputs = new Dictionary<string, string[]>
		{
			["bitmap"] = new string[]
			{
				"stbtt__handle_clipped_edge",
				"stbtt__rasterize_sorted_edges",
				"stbtt__fill_active_edges_new",
				"stbtt__sort_edges_ins_sort",
				"stbtt__sort_edges_quicksort",
				"stbtt__sort_edges",
				"stbtt__bitmap",
				"stbtt__edge",
				"stbtt__active_edge",
			},
			["buf"] = new string[]
			{
				"stbtt__buf",
				"stbtt__new_buf",

			},
			["charString"] = new string[]
			{
				"stbtt__csctx"
			},
			["fontInfo"] = new string[]
			{
				"stbtt_fontinfo",
				"stbtt__close_shape",
				"stbtt__GetCoverageIndex",
				"stbtt__GetGlyphClass",
				"stbtt_kerningentry",
			},
			["rectPack"] = new string[]
			{
				"stbrp_context",
				"stbtt_pack_context",
				"stbtt_pack_range",
				"stbrp_node",
				"stbrp_rect",
			},
			["heap"] = new string[]
			{
				"stbtt__hheap",
				"stbtt__hheap_chunk"
			}
		};

		private static bool OwnedByClass(this string value, string cls)
		{
			return value.Contains(": *mut " + cls);
		}

		private static void Write(Dictionary<string, string> input, Dictionary<string, string> output)
		{
			var keys = (from string k in input.Keys orderby k select k).ToArray();
			foreach (var key in keys)
			{
				string outputKey = null;
				foreach (var pair2 in _outputs)
				{
					foreach (var prefix in pair2.Value)
					{
						if (key.StartsWith(prefix))
						{
							outputKey = pair2.Key;
							goto found;
						}
					}
				}
			found:

				var value = input[key];
				if (outputKey == null)
				{
					if (value.OwnedByClass("stbtt__bitmap"))
					{
						outputKey = "bitmap";
					}
					else if (value.OwnedByClass("stbtt__buf"))
					{
						outputKey = "buf";
					}
					else if (value.OwnedByClass("stbtt__csctx"))
					{
						outputKey = "charString";
					}
					else if (value.OwnedByClass("stbtt_fontinfo"))
					{
						outputKey = "fontInfo";
					}
					else if (value.OwnedByClass("stbrp_context") ||
						value.OwnedByClass("stbtt_pack_context"))
					{
						outputKey = "rectPack";
					}
					else if (value.OwnedByClass("stbtt__hheap"))
					{
						outputKey = "heap";
					}
				}

				if (outputKey == null)
				{
					outputKey = "common";
				}

				if (!output.ContainsKey(outputKey))
				{
					output[outputKey] = string.Empty;
				}

				output[outputKey] += value;
			}
		}

		private static string PostProcess(string data)
		{
			return data;
		}

		static void Process()
		{
			var parameters = new RustConversionParameters
			{
				InputPath = @"stb_truetype.h",
				Defines = new[]
				{
					"STB_TRUETYPE_IMPLEMENTATION",
				},
				SkipStructs = new string[]
				{
				},
				SkipGlobalVariables = new string[]
				{
				},
				SkipFunctions = new string[]
				{
				},
			};

//			var dump = TextCodeConverter.Convert(parameters.InputPath, parameters.Defines);
//			File.WriteAllText(@"..\..\..\..\..\..\StbTrueType.txt", dump);

			var result = RustCodeConverter.Convert(parameters);

			// Post processing
			Logger.Info("Post processing...");

			var outputFiles = new Dictionary<string, string>();
			Write(result.UnnamedEnumValues, outputFiles);
			Write(result.GlobalVariables, outputFiles);
			Write(result.Structs, outputFiles);
			Write(result.StructDefaults, outputFiles);
			Write(result.Functions, outputFiles);

			foreach (var pair in outputFiles)
			{
				var data = PostProcess(pair.Value);

				var sb = new StringBuilder();
				sb.AppendLine(string.Format("// Generated by Hebron at {0}", DateTime.Now));
				sb.AppendLine();

				sb.AppendLine("use std;");
				sb.AppendLine("use c_runtime;");
				sb.AppendLine("use crate::*;");

				sb.AppendLine();
				sb.Append(data);

				File.WriteAllText(@"..\..\..\..\..\..\stb_truetype_rust\src\stb_truetype_" + pair.Key + ".rs", sb.ToString());
			}
		}

		static void Main(string[] args)
		{
			try
			{
				Process();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex.Message);
				Console.WriteLine(ex.StackTrace);
			}

			Console.WriteLine("Finished. Press any key to quit.");
			Console.ReadKey();
		}
	}
}