[package]
name = "baram-xiao"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xiao"
path = "src/main.rs"

[dependencies]
baram-bsd = { path = "../baram-bsd" }
baram-core = { path = "../baram-core" }
baram-font = { path = "../baram-font", default-features = false, features = ["bdf"] }
baram-warp4 = { path = "../baram-warp4", default-features = false, features = ["bdf"] }
nano-system = { path = "../nano-system" }
uefi = { workspace = true }
