#include "ui_data.h"

const char *const warp_ui_code =
"screen(\n"
"    id:main\n"
"\n"
"    Header(\n"
"    text:\"Warp Demo\"\n"
"\n"
"    button(\n"
"        --headerText:\"こんにちは\"\n"
"        text:\"みなさん，\"+--headerText\n"
"    )\n"
"    )\n"
"\n"
"    text(\n"
"    text:\"これは新しい、ネイティブとWeb技術が融合する言語です。気になる反応は\"+--mainText\n"
"    --mainText:\"...\"\n"
"    )\n"
"\n"
"    card(\n"
"    text:\"内容変更\"\n"
"    text(\n"
"        text:\"クリックにより表示内容が変更されます\"\n"
"    )\n"
"        button(\n"
"            text:\"GOOD\"\n"
"            oneClick:--mainText=\"良いみたいです!\"\n"
"        )\n"
"        button(\n"
"            text:\"BAD\"\n"
"            oneClick:--mainText=\"あまり良くないようですね。\"\n"
"        )\n"
"    )\n"
"\n"
"    card(\n"
"        text:\"button\"\n"
"        text(\n"
"            text:\"通常ボタン\"\n"
"        )\n"
"        card(\n"
"            text:\"使用例\"\n"
"            color:black\n"
"            text(\n"
"                text:\"button\\(\n"
"                \\n\\ \\ text\\:\\\"戻る\\\"\n"
"                \\n\\)\"\n"
"            )\n"
"        )\n"
"    )\n"
")\n"
"";
